server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          predicates:
            - Path=/payment/circuit/**   #断言,路径相匹配的进行路由
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://CLOUD-HYSTRIX-PAYMENT-SERVICE

        - id: payment_routh2
          predicates:
            - Path=/payment/hystrix/**   #断言,路径相匹配的进行路由
          #uri: http://localhost:8001
          uri: lb://CLOUD-HYSTRIX-PAYMENT-SERVICE

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka